include:
  - proxy.yaml

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: web 
    restart: always
    networks:
      backend:
        ipv4_address: 172.20.0.5
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: mysql:8
    restart: always
    env_file:
      - .env
    networks:
      backend:
        ipv4_address: 172.20.0.10
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  backend:
    name: backend
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  mysql-data:
